### ISSUE TITLE
Confidant does not recognize my external hard disk

### ISSUE THREAD

**Issue by taeyonlee** [confidantstation/Confidant-Station#10]
![Confidant_harddisk_Config](https://user-images.githubusercontent.com/42931121/57907771-f31f4200-78b0-11e9-8aff-0ef589c3d24b.jpg)

I did the installation .... I did not have to format the HDD ... is that normal ? I was able to upload files .
I am running confidant V:0.2.6 (build97) app ? is this the correct one. 

Cris Fenix, [17.05.19 04:01]
I did the installation .... I did not have to format the HDD ... is that normal ? I was able to upload files .

I am running confidant V:0.2.6 (build97) app ? is this the correct one?
I got the cable today.  I hooked up the hard drive to my laptop - the laptop made a sound like it knew something was plugged in, but I do not see the drive in my file explorer.  However I did see it in the "safely remove hardware" icon.  WD sent me a diagnostic program to test the hard drive and I am running it now - it did see the hard drive.  The test will take over 14 hours so I will wait.  I am curious why it is not showing up in the file explorer.  Perhaps it needs to be formatted first, and formatted first for Confidant to see it?  Still does not explain the clicking sound I heard when it was in Confidant (which I do not hear now as it is being scanned).

**Comment by coolc4** [comment]
version:0.1.32
已修正
