### ISSUE TITLE
The new user activates the node and sends a push message to the owner,like wechat

### ISSUE THREAD

**Issue by qlinkDev** [confidantstation/Confidant-Station#24]
The new user activates the node and sends a push message to the owner,like wechat

**Comment by coolc4** [comment]
新用户注册成功，节点模拟admin用户发送一条欢迎消息，点对点对话
因为我们当前的加密机制，节点不知道用户的密钥，只能用模拟方式发送一个base64编码的，prikey和nonce都是32个“=”，需要app支持这种消息的解码
待联调

**Comment by coolc4** [comment]
2020 03月版本已经完成并集成该功能，对应节点版本号 V0.1.132
