### ISSUE TITLE
confidant UI及内容体验改进建议

### ISSUE THREAD

**Issue by chenkai454622685** [confidantstation/Confidant-Station#26]
### **Confidant UI及内容体验改进建议**

**一、 项目名称：Confidant
二、 项目环境：iOS、Android 
三、 具体建议如下：** 

1、部分UI改版修改没有完成，聊天、通讯录、我的，风格不统一。

2、邮箱功能和confidant好友功能融合没有完善，好友整理里没有发邮寄和填写邮箱资料等功能。

3、加密微信和加密短信功能Android 才能使用。加密微信和加密相册差不多，短信加密像记事本没有记事本好理解好用。

4、添加好友搜索邮箱地址是否可以添加 Confidant 好友，现在添加了Confidant 好友就有他使用的邮箱信息。

5、消息页左上角不能点进去切换节点，与邮箱页不一致。

6、聊天功能没有电话和视频。

**Comment by coolc4** [comment]
Temporarily closed
Link to other specific issues
