### ISSUE TITLE
Confidant现有功能bug及新功能建议

### ISSUE THREAD

**Issue by taeyonlee** [confidantstation/Confidant-Station#27]
iOS环境
版本号： V: 0.4.3 (Build 101)

1. 某些带图片邮件打开 （QLC双周报）邮件全文的图片都是闪现一下后即消失， 转发该邮件时图片出现。其他邮件的图片则可以正常显示。
2. 宽度没有自适应屏幕，邮件内容过宽
3. Messages下的历史信息记录为空
4. 长时间不打开Confidant,邮件信息没有推送
5. 邮件Invite friends发送邮件给非用户，长按二维码不识别（应改为下载链接）
6. 带附件邮件多次往来后，原来邮件没有附件
7. 邮件附件无法下载
8. 添加Gmail成功后，下拉邮件显示 Failed to pull email，多次尝试无法拉取邮件
新功能建议：
Phone calling.
参考竞品, silent circle (社区成员推荐，南美地区政府官员用的付费软件，企业付费软件服务，核心功能为加密信息，电话和管理中心）

**Comment by coolc4** [comment]
Temporarily closed
Link to other specific issues
